2024-03-25 11:44:55,851 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2024-03-25 11:44:55,852 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2024-03-25 11:44:55,853 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "hardiksharmah73@gmail.com", --configuration: "default", --format: "value(name)", PROJECT_ID_OR_NUMBER: "pegasus-401519"]
2024-03-25 11:44:55,864 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-03-25 11:44:55,866 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:44:55,866 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/pegasus-401519?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:44:57,394 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-03-25 11:44:57,395 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:44:57,395 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/pegasus-401519?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:45:02,342 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-03-25 11:45:02,342 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:45:02,342 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/pegasus-401519?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/pegasus-401519?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0091f87490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2024-03-25 11:45:09,578 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2024-03-25 11:45:11,156 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/pegasus-401519?alt=json HTTP/1.1" 200 None
2024-03-25 11:45:11,158 DEBUG    root            Chosen display Format:default value(name)
2024-03-25 11:45:11,158 INFO     root            Display format: "default value(name)"
2024-03-25 11:45:11,159 INFO     ___FILE_ONLY___ PEGASUS

