2023-10-10 02:12:09,220 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2023-10-10 02:12:09,222 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'images']
2023-10-10 02:12:09,240 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'images', 'list']
2023-10-10 02:12:09,242 DEBUG    root            Running [gcloud.compute.images.list] with arguments: [--filter: "location:(asia-south1)", --project: "your-project-id"]
2023-10-10 02:12:09,366 INFO     root            client_filter='location:(asia-south1)' server_filter=None
2023-10-10 02:12:09,367 INFO     root            client_filter='(location:(asia-south1))' server_filter=None
2023-10-10 02:12:09,368 DEBUG    root            Chosen display Format:    table(
      name,
      selfLink.map().scope(projects).segment(0):label=PROJECT,
      family,
      deprecated.state:label=DEPRECATED,
      status
    )
2023-10-10 02:12:09,369 INFO     root            Display format: "    table(
      name,
      selfLink.map().scope(projects).segment(0):label=PROJECT,
      family,
      deprecated.state:label=DEPRECATED,
      status
    )"
2023-10-10 02:12:09,376 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-10 02:12:11,413 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "POST /batch/compute/v1 HTTP/1.1" 200 None
2023-10-10 02:12:18,018 INFO     ___FILE_ONLY___ Enabling service [compute.googleapis.com] on project [your-project-id]...

2023-10-10 02:12:18,040 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): serviceusage.googleapis.com:443
2023-10-10 02:12:19,866 DEBUG    urllib3.connectionpool https://serviceusage.googleapis.com:443 "POST /v1/projects/your-project-id/services/compute.googleapis.com:enable?alt=json HTTP/1.1" 403 None
2023-10-10 02:12:19,870 DEBUG    root            Chosen display Format:default
2023-10-10 02:12:19,886 DEBUG    root            Chosen display Format:default
2023-10-10 02:12:19,875 DEBUG    root            (gcloud.compute.images.list) PERMISSION_DENIED: Permission denied to enable service [compute.googleapis.com]
Help Token: AVzH8v1pq4zBW7yuF7fx4kJWlxZnyDebHmAbIzlt3lf0-Yu3PTNKuuXj8RDsm3bQX8HCdYeF0mheZoEZ_tMWh1cxy_1lj_8exoV13oC8apx5onD7
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=your-project-id
    type: googleapis.com
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com
  metadata:
    permission: serviceusage.services.enable
    resource: your-project-id
    service: serviceusage.googleapis.com
  reason: AUTH_PERMISSION_DENIED
Traceback (most recent call last):
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/serviceusage.py", line 589, in EnableApiCall
    return client.services.Enable(request)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/serviceusage/v1/serviceusage_v1_client.py", line 263, in Enable
    return self._RunMethod(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://serviceusage.googleapis.com/v1/projects/your-project-id/services/compute.googleapis.com:enable?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Mon, 09 Oct 2023 20:42:19 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "Permission denied to enable service [compute.googleapis.com]\nHelp Token: AVzH8v1pq4zBW7yuF7fx4kJWlxZnyDebHmAbIzlt3lf0-Yu3PTNKuuXj8RDsm3bQX8HCdYeF0mheZoEZ_tMWh1cxy_1lj_8exoV13oC8apx5onD7",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
        "violations": [
          {
            "type": "googleapis.com",
            "subject": "?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=your-project-id"
          }
        ]
      },
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "AUTH_PERMISSION_DENIED",
        "domain": "serviceusage.googleapis.com",
        "metadata": {
          "service": "serviceusage.googleapis.com",
          "permission": "serviceusage.services.enable",
          "resource": "your-project-id"
        }
      }
    ]
  }
}
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    display_info=self.ai.display_info).Display()
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 483, in Display
    self._printer.Print(self._resources)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 298, in Print
    for resource in resources:
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 211, in __next__
    item = self._NextItem()
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/core/util/peek_iterable.py", line 183, in _NextItem
    return next(self._iterable)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/surface/compute/images/list.py", line 148, in _FilterDeprecated
    for image in images:
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/lister.py", line 1151, in __call__
    for item in request_helper.ListJson(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 247, in ListJson
    for item in _ListCore(requests, http, batch_url, errors, _HandleJsonList):
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/request_helper.py", line 149, in _ListCore
    responses, request_errors = batch_helper.MakeRequests(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 106, in MakeRequests
    responses = batch_request.Execute(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 226, in Execute
    batch_http_request.Execute(http)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/batch.py", line 506, in Execute
    self.__callback(response, exception)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/batch_helper.py", line 74, in BatchCheck
    apis.PromptToEnableApi(project, service_token, exception,
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 187, in PromptToEnableApi
    api_enable_attempted = api_enablement.PromptToEnableApi(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/api_enablement.py", line 77, in PromptToEnableApi
    enable_api.EnableService(project, service_token)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/enable_api.py", line 66, in EnableService
    op = serviceusage.EnableApiCall(project_id, service_name)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/serviceusage.py", line 592, in EnableApiCall
    exceptions.ReraiseError(e,
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/exceptions.py", line 175, in ReraiseError
    core_exceptions.reraise(klass(api_lib_exceptions.HttpException(err)))
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/six/__init__.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/services/serviceusage.py", line 589, in EnableApiCall
    return client.services.Enable(request)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/serviceusage/v1/serviceusage_v1_client.py", line 263, in Enable
    return self._RunMethod(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 737, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 743, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 609, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
googlecloudsdk.api_lib.services.exceptions.EnableServicePermissionDeniedException: PERMISSION_DENIED: Permission denied to enable service [compute.googleapis.com]
Help Token: AVzH8v1pq4zBW7yuF7fx4kJWlxZnyDebHmAbIzlt3lf0-Yu3PTNKuuXj8RDsm3bQX8HCdYeF0mheZoEZ_tMWh1cxy_1lj_8exoV13oC8apx5onD7
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=your-project-id
    type: googleapis.com
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com
  metadata:
    permission: serviceusage.services.enable
    resource: your-project-id
    service: serviceusage.googleapis.com
  reason: AUTH_PERMISSION_DENIED
2023-10-10 02:12:19,888 ERROR    root            (gcloud.compute.images.list) PERMISSION_DENIED: Permission denied to enable service [compute.googleapis.com]
Help Token: AVzH8v1pq4zBW7yuF7fx4kJWlxZnyDebHmAbIzlt3lf0-Yu3PTNKuuXj8RDsm3bQX8HCdYeF0mheZoEZ_tMWh1cxy_1lj_8exoV13oC8apx5onD7
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - subject: ?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=your-project-id
    type: googleapis.com
- '@type': type.googleapis.com/google.rpc.ErrorInfo
  domain: serviceusage.googleapis.com
  metadata:
    permission: serviceusage.services.enable
    resource: your-project-id
    service: serviceusage.googleapis.com
  reason: AUTH_PERMISSION_DENIED
